name = "journal"
compatibility_date = "2026-02-16"
workers_dev = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Custom domain
[[routes]]
pattern = "darinhenry.ai"
custom_domain = true
